DA_ASP/DA_ASP/Controllers/AcCountController.cs
using DA_ASP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DA_ASP.Controllers
{
    public class AcCountController : Controller
    {
        dbBanDTDataContext data = new dbBanDTDataContext();
        // GET: AcCount
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        //POST: ham dangky(post) nhan du lieu tu trang dang ky vaf thuc hien viec tao moi du lieu
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, TKKHACHHANG kh)
        {
            var TenUser = collection["TenUser"];
            var SDTUser = collection["SDTUser"];
            var Email = collection["Email"];
            var DiaChi = collection["DiaChi"];
            var MKUser = collection["MKUser"];
            var MKUserNL = collection["MKUserNL"];
            var NgaySinh = String.Format("{0:mm/dd/yyyy}", collection["NgaySinh"]);

            if (String.IsNullOrEmpty(TenUser))
            {
                ViewData["Loi2"] = "Ten khach hang khong duoc de trong !!!";
            }
            else if (String.IsNullOrEmpty(SDTUser))
            {
                ViewData["Loi3"] = "Phai nhap so dien thoai khach hang !!!";
            }
            else if (String.IsNullOrEmpty(Email))
            {
                ViewData["Loi4"] = "Email khach hang khong duoc de trong !!!";
            }
            else if (String.IsNullOrEmpty(DiaChi))
            {
                ViewData["Loi5"] = "Phai nhap dia chi khach hang !!!";
            }
            else if (String.IsNullOrEmpty(MKUser))
            {
                ViewData["Loi6"] = "Phai nhap mat khau khach hang !!!";
            }
            else if (String.IsNullOrEmpty(MKUserNL))
            {
                ViewData["Loi7"] = "Phai nhap lai mat khau khach hang !!!";
            }
            else
            {
                //gan gia tri cho doi tuong duoc tao moi (kh)
                kh.TenUser = TenUser;
                kh.SDTUser = SDTUser;
                kh.Email = Email;
                kh.DiaChi = DiaChi;
                kh.MKUser = MKUser;
                kh.NgaySinh = NgaySinh;
                data.TKKHACHHANGs.InsertOnSubmit(kh);
                data.SubmitChanges();
                return RedirectToAction("DangNhap");
            }
            return this.DangKy();
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var SDTUser = collection["SDTUser"];
            var MKUser = collection["MKUser"];
            if (String.IsNullOrEmpty(SDTUser))
            {
                ViewData["Loi1"] = "Phai nhap so dien thoai !!!";
            }else if (String.IsNullOrEmpty(MKUser))
            {
                ViewData["Loi2"] = "Phai nhap mat khau !!!";
            }
            else
            {
                //Gan gia tri cho doi tuong duoc tao moi (kh)
                TKKHACHHANG kh = data.TKKHACHHANGs.SingleOrDefault(n => n.SDTUser == SDTUser && n.MKUser == MKUser);
                if(kh != null)
                {
                    ViewBag.Thongbao = "Dang nhap thanh cong";
                    Session["User"] = kh;
                }
                else
                {
                    ViewBag.Thongbao = "Ten dang nhap hoat mat khau khong dung";
                }
                return View();
            }
            return View();
        }
    } 
}

DA_ASP/DA_ASP/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DA_ASP.Models;

namespace DA_ASP.Controllers
{
    public class ShopController : Controller
    {
        dbBanDTDataContext data = new dbBanDTDataContext();

        private List<SANPHAM> listSP(int sl)
        {
            return data.SANPHAMs.Take(sl).ToList();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Hang()
        {
            return PartialView(from hang in data.NHASXes select hang);
        }

        public ActionResult SanPhamNew()
        {
            return View(from sp in data.SANPHAMs orderby sp.MaSP descending select sp);
        }

        public ActionResult SpFeatured()
        {
            return View(listSP(10));
        }

        public ActionResult SpHang(string id)
        {
                return View(from sp in data.SANPHAMs where sp.MaSX == id select sp);
           
        }

        public ActionResult Detail(int id)
        {
            return View((from sp in data.SANPHAMs where sp.MaSP == id select sp).Single());
        }

        public ActionResult Brand()
        {
            return PartialView(from h in data.NHASXes select h);
        }

        public ActionResult Products()
        {
            return View();
        }

        public ActionResult ProductNew()
        {
            return PartialView(from sp in data.SANPHAMs orderby sp.MaSP descending select sp);
        }

        public ActionResult Product()
        {
                return View(from sp in data.SANPHAMs select sp);
        }

        public ActionResult ProductInBrand(string id)
        {
            return PartialView(from sp in data.SANPHAMs where sp.MaSX == id select sp);
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

DA_ASP/DA_ASP/Views/Shared/_Layout.cshtml
        @RenderBody()
        

DA_ASP/DA_ASP/Views/Shared/_LayoutShop.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>@ViewBag.Title</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="~/Content/bootstrap.min.css" />

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href="~/Content/slick.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/slick-theme.css" />

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href="~/Content/nouislider.min.css" />

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="~/Content/font-awesome.min.css">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="~/Content/style.css" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <!-- HEADER -->
    <header>
        <!-- TOP HEADER -->
        <div id="top-header">
            <div class="container">
                <ul class="header-links pull-left">
                    <li><a href="#"><i class="fa fa-phone"></i> +021-95-51-84</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
                    <li><a href="#"><i class="fa fa-map-marker"></i> 1734 Stonecoal Road</a></li>
                </ul>
                <ul class="header-links pull-right">
                    <li><a href="#"><i class="fa fa-dollar"></i> USD</a></li>
                    <li><a href="@Url.Action("DangNhap","AcCount")"><i class="fa fa-user-o"></i> My Account</a></li>
                </ul>
            </div>
        </div>
        <!-- /TOP HEADER -->
        <!-- MAIN HEADER -->
        <div id="header">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <!-- LOGO -->
                    <div class="col-md-3">
                        <div class="header-logo">
                            <a href="#" class="logo">
                                <img src="~/img/logo.png" alt="">
                            </a>
                        </div>
                    </div>
                    <!-- /LOGO -->
                    <!-- SEARCH BAR -->
                    <div class="col-md-6">
                        <div class="header-search">
                            <form>
                                <select class="input-select">
                                    <option value="0">All Categories</option>
                                    <option value="1">Category 01</option>
                                    <option value="1">Category 02</option>
                                </select>
                                <input class="input" placeholder="Search here">
                                <button class="search-btn">Search</button>
                            </form>
                        </div>
                    </div>
                    <!-- /SEARCH BAR -->
                    <!-- ACCOUNT -->
                    <div class="col-md-3 clearfix">
                        <div class="header-ctn">
                            <!-- Wishlist -->
                            <div>
                                <a href="#">
                                    <i class="fa fa-heart-o"></i>
                                    <span>Your Wishlist</span>
                                    <div class="qty">2</div>
                                </a>
                            </div>
                            <!-- /Wishlist -->
                            <!-- Cart -->
                            <div class="dropdown">
                                @Html.Action("GioHangView","GioHang")
                            </div>
                            <!-- /Cart -->
                            <!-- Menu Toogle -->
                            <div class="menu-toggle">
                                <a href="#">
                                    <i class="fa fa-bars"></i>
                                    <span>Menu</span>
                                </a>
                            </div>
                            <!-- /Menu Toogle -->
                        </div>
                    </div>
                    <!-- /ACCOUNT -->
                </div>
                <!-- row -->
            </div>
            <!-- container -->
        </div>
        <!-- /MAIN HEADER -->
    </header>
    <!-- /HEADER -->
    <!-- NAVIGATION -->
    <nav id="navigation">
        <!-- container -->
        <div class="container">
            <!-- responsive-nav -->
            <div id="responsive-nav">
                <!-- NAV -->
                <ul class="main-nav nav navbar-nav">
                    <li class="active"><a href="@Url.Action("Index","Shop")">Home</a></li>
                    <li><a href="@Url.Action("About","Shop")">About</a></li>
                    <li><a href="@Url.Action("Products","Shop")">Products</a></li>
                    <li><a href="@Url.Action("Contact","Shop")">Contact</a></li>
                </ul>
                <!-- /NAV -->
            </div>
            <!-- /responsive-nav -->
        </div>
        <!-- /container -->
    </nav>
    <!-- /NAVIGATION -->
    <!-- SECTION -->
    <div>
        @RenderBody()
    </div>
    <!-- /SECTION -->
    <!-- NEWSLETTER -->
    <div id="newsletter" class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="newsletter">
                        <p>Sign Up for the <strong>NEWSLETTER</strong></p>
                        <form>
                            <input class="input" type="email" placeholder="Enter Your Email">
                            <button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
                        </form>
                        <ul class="newsletter-follow">
                            <li>
                                <a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /NEWSLETTER -->
    <!-- FOOTER -->
    <footer id="footer">
        <!-- top footer -->
        <div class="section">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">About Us</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
                            <ul class="footer-links">
                                <li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
                                <li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
                                <li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Categories</h3>
                            <ul class="footer-links">
                                <li><a href="#">Hot deals</a></li>
                                <li><a href="#">Laptops</a></li>
                                <li><a href="#">Smartphones</a></li>
                                <li><a href="#">Cameras</a></li>
                                <li><a href="#">Accessories</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="clearfix visible-xs"></div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Information</h3>
                            <ul class="footer-links">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Contact Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Orders and Returns</a></li>
                                <li><a href="#">Terms & Conditions</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Service</h3>
                            <ul class="footer-links">
                                <li><a href="#">My Account</a></li>
                                <li><a href="#">View Cart</a></li>
                                <li><a href="#">Wishlist</a></li>
                                <li><a href="#">Track My Order</a></li>
                                <li><a href="#">Help</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /top footer -->
        <!-- bottom footer -->
        <!-- /bottom footer -->
    </footer>
    <!-- /FOOTER -->
    <!-- jQuery Plugins -->
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/slick.min.js"></script>
    <script src="~/Scripts/nouislider.min.js"></script>
    <script src="~/Scripts/jquery.zoom.min.js"></script>
    <script src="~/Scripts/main.js"></script>

</body>
</html>